FROM ubuntu:16.04

RUN mkdir /plex
WORKDIR /plex

ENV PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR /plex/Library/Application Support
ENV PLEX_HOME=/plex

RUN apt-get update && \
    apt-get install -qy dbus avahi-daemon wget curl && \
    curl -L 'https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu' -o /tmp/plexmediaserver.deb && \
    dpkg -i /tmp/plexmediaserver.deb && rm -f /tmp/plexmediaserver.deb && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY plexmediaserver /etc/default/plexmediaserver

CMD ["/usr/sbin/start_pms"]
