FROM debian:jessie

# Install transmission
RUN export DEBIAN_FRONTEND='noninteractive' && \
    apt-get update -qq && \
    apt-get install -qqy --no-install-recommends transmission-daemon curl wget vim \
                $(apt-get -s dist-upgrade|awk '/^Inst.*ecurity/ {print $2}') && \
    apt-get clean && \
    dir="/var/lib/transmission-daemon" && \
    rm $dir/info && \
    mv $dir/.config/transmission-daemon $dir/info && \
    rmdir $dir/.config && \
    usermod -d $dir debian-transmission && \
    [ -d $dir/downloads ] || mkdir -p $dir/downloads && \
    [ -d $dir/incomplete ] || mkdir -p $dir/incomplete && \
    [ -d $dir/info/blocklists ] || mkdir -p $dir/info/blocklists && \
    file="$dir/info/settings.json" && \
    sed -i '/"peer-port"/a\    "peer-socket-tos": "lowcost",' $file && \
    sed -i '/"port-forwarding-enabled"/a\    "queue-stalled-enabled": true,' $file && \
    sed -i '/"queue-stalled-enabled"/a\    "ratio-limit-enabled": true,' $file && \
    sed -i '/"rpc-whitelist"/a\    "speed-limit-up": 0,' $file && \
    sed -i '/"speed-limit-up"/a\    "speed-limit-up-enabled": true,' $file && \
    sed -i '/"download-queue-enabled": true/"download-queue-enabled": false,' $file && \
    chown -Rh debian-transmission. $dir && \
    rm -rf /var/lib/apt/lists/* /tmp/* && \
    mv $dir /transmission

WORKDIR /transmission
COPY transmission.sh /transmission/transmission.sh

VOLUME ["/transmission"]

EXPOSE 9091 51413/tcp 51413/udp

CMD ["./transmission.sh"]
